version: "3.9"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
